
const MODEL="openai/gpt-oss-120b:fastest";
const HF_URL="https://router.huggingface.co/v1/chat/completions";
const cors=o=>({"Access-Control-Allow-Origin":o||"*","Access-Control-Allow-Methods":"GET,POST,DELETE,OPTIONS","Access-Control-Allow-Headers":"Content-Typeconst json=(x,s=200,o="*")=>new Response(JSON.stringify(x),{status:s,headers:cors(o)});
const now=()=>new Date().toISOString();
const id=()=>crypto.randomUUID();
async function hash(s){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStasync function sign(payload,secret){const data=btoa(JSON.stringify(payload));const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(secretasync function verify(token,secret){try{const [data,s]=token.split(".");const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{naasync function admin(req,e){const t=(req.headers.get("Authorization")||"").replace("Bearer ","");return t?await verify(t,e.SESSION_SECRET):null}
async function sendTelegram(e,chat,text){if(!chat||!e.TELEGRAM_BOT_TOKEN)return;await fetch(`https://api.telegram.org/bot${e.TELEGRAM_BOT_TOKEN}/sendMessaasync function ai(e,b){const prompt=`Analiza este comprobante de Pago Movil como filtro antifraude. NO afirmes que el dinero llego al banco. Extrae banco,const r=await fetch(HF_URL,{method:"POST",headers:{"Authorization":`Bearer ${e.HF_TOKEN}`,"Content-Type":"application/json"},body:JSON.stringify({model:MOconst t=await r.text();if(!r.ok)throw Error("Hugging Face rechazó el análisis");let j=JSON.parse(t),s=j?.choices?.[0]?.message?.content||"",m=s.match(/\{[export default{async fetch(req,e){const o=req.headers.get("Origin")||"*";if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(o)});try{
if(u.pathname==="/health")return json({ok:true},200,o);
if(u.pathname==="/api/hotels"&&req.method==="GET"){const {results}=await e.DB.prepare("SELECT id,name,category,state,city,zone,level,normal,price,deposit,if(u.pathname==="/api/admin/login"&&req.method==="POST"){const b=await req.json();if(!e.ADMIN_PASSWORD||b.password!==e.ADMIN_PASSWORD)return json({error:"const ap=await admin(req,e);
if(u.pathname==="/api/admin/hotels"&&req.method==="POST"){if(!ap)return json({error:"No autorizado"},401,o);const b=await req.json(),hid=id();await e.DB.plet m=u.pathname.match(/^\/api\/admin\/hotels\/([^/]+)$/);if(m&&req.method==="DELETE"){if(!ap)return json({error:"No autorizado"},401,o);await e.DB.preparm=u.pathname.match(/^\/api\/admin\/hotels\/([^/]+)\/telegram-link$/);if(m&&req.method==="POST"){if(!ap)return json({error:"No autorizado"},401,o);const toif(u.pathname==="/api/telegram/webhook"&&req.method==="POST"){const upd=await req.json(),msg=upd.message;if(msg?.text?.startsWith("/start HOTEL_")){const if(u.pathname==="/api/reservations"&&req.method==="POST"){const b=await req.json(),h=await e.DB.prepare("SELECT * FROM hotels WHERE id=? AND active=1").bim=u.pathname.match(/^\/api\/reservations\/([^/]+)\/proof$/);if(m&&req.method==="POST"){const b=await req.json(),r=await e.DB.prepare("SELECT r.*,h.name hoif(u.pathname==="/api/analyze-payment"&&req.method==="POST"){if(!e.HF_TOKEN)return json({error:"HF_TOKEN no configurado"},500,o);const b=await req.json();return json({error:"Ruta no encontrada"},404,o)
}catch(err){return json({error:err.message||"Error interno"},500,o)}
}};
